on: 
  push:
    branches:
    - main
    
name: deploy test build

jobs:
  deploy: 
    name: deploy
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: build an d push to docker
      uses: docker/build-push-action@v1
      with: 
         username: ${{ secrets.DOCKERHUB_USERNAME }} 
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
         repository: ${{ github.repository }}
         tags: prueba-buildeo-develop
